sudo: required

services:
  - docker

cache:
  directories:
  - $HOME/.m2

before_install:
  - docker build -t tasks-delivery/network .

script:
  - docker run --rm -v $(pwd):/opt/rocksaw -v $HOME/.m2:/root/.m2 tasks-delivery/network
